name: kura
version: "3.x"
version-script: |
    [ "x$(grep  -E '^version=.*SNAPSHOT'  prime/kura/kura/kura.properties)" != "x" ] \
        && echo $(grep '^version=' prime/kura/kura/kura.properties | awk -F '=' '{ print $2}')-$(git --git-dir=parts/kura/build/.git describe --tags | awk -F '-' '{ print $2"-"$3}') \
        || grep '^version=' prime/kura/kura/kura.properties | awk -F '=' '{ print $2}'
summary: kura
description: |
 kura

confinement: strict
grade: stable

plugs:
  client:
    interface: bluez
slots:
  service:
    interface: bluez

apps:
#    service:
#        command: kura-control start_kura_backgroud.sh
#        daemon: simple
#        plugs:
#            - home
#            - io-ports-control
#            - hardware-observe
#            - firewall-control
#            - network-bind
#            - network-control
#            - network-manager
#            - network-setup-control
#            - process-control
#            - removable-media
#            - system-observe
#            - time-control

    kura:
        command: kura/bin/start_kura.sh
        plugs: &default-plugs [home , io-ports-control, hardware-observe, firewall-control, network-bind, network-control, network-manager, network-setup-control, process-control, removable-media, system-observe, time-control]

    kura-init:
        command: kura-init start
        stop-command: kura-init stop
        daemon: simple
        plugs: *default-plugs


    kura-debug:
        command: kura/bin/start_kura_debug.sh
        plugs: *default-plugs

    help:
        command: bin/help

    bluez:
        command: "usr/lib/bluetooth/bluetoothd -E"
        daemon: simple
        plugs:
            - uhid
        slots:
            - service

    obex:
        command: "usr/lib/bluetooth/obexd"
        daemon: simple
        slots:
            - service

parts:
    kura:
        # use custom pluging, it will build what we need
        plugin: nil
        source: https://github.com/eclipse/kura.git
        # source: https://github.com/kubiko/kura.git
        source-branch: develop
        stage-packages:
            - libudev1
            - dos2unix
            - telnet
            - minicom
            - setserial
            - powertop
            - openvpn
            - monit
            - coreutils
            - unzip
            - inetutils-telnet
            - socat
            - usbutils
            - nano
        build-packages:
            - unzip
            - openjdk-8-jdk-headless
            - maven
            - gawk
        # first tweak source for snap building
        prepare: |
            sed -i \
                  -e 's#name="target.device" value=".*"#name="target.device" value="ubuntu-snap"#g' \
                  -e 's#name="native.tag" value=".*"#name="native.tag" value="x86_64"#g' \
                  -e 's#name="kura.os.version" value=".*"#name="kura.os.version" value="ubuntu"#g' \
                  -e 's#name="kura.arch" value=".*"#name="kura.arch" value="x86_64"#g' \
                  -e 's#name="kura.install.dir" value=".*"#name="kura.install.dir" value="/snap/'"${SNAPCRAFT_PROJECT_NAME}"'/current"#g' \
                kura/distrib/pom.xml
            sed -i \
                  -e 's#osgi.instance.area=.*#osgi.instance.area=/var/snap/'"${SNAPCRAFT_PROJECT_NAME}"'/current/data#g' \
                  -e 's#org.osgi.framework.storage=.*#org.osgi.framework.storage=/var/snap/'"${SNAPCRAFT_PROJECT_NAME}"'/current/data#g' \
                kura/distrib/src/main/osgi/equinox_3.11.1/configuration/config.ini
            sed -i \
                  -e 's#Raspberry-Pi#snappy#g' \
                  -e 's#kura.tmp=.*#kura.tmp=/var/snap/'"${SNAPCRAFT_PROJECT_NAME}"'/current/tmp#g' \
                kura/distrib/src/main/resources/raspberry-pi-2*/kura.properties
            sed -i \
                  -e 's#/var/log/kura#/var/snap/'"${SNAPCRAFT_PROJECT_NAME}"'/current/log/kura#g' \
                kura/distrib/src/main/resources/raspberry-pi-2*/log4j.properties
            sed -i \
                  -e 's#iptables_config_file=.*#iptables_config_file=${SNAP_COMMON}/etc/sysconfig/iptables#g' \
                  -e 's#/etc/init.d/firewall_cust#${SNAP_COMMON}/etc/init.d/firewall_cust#g' \
                kura/distrib/src/main/resources/raspberry-pi-2*/firewall.init
            sed -i \
                  -e 's#/var/run/#${SNAP_DATA}/run/#g' \
                kura/distrib/src/main/resources/common/*.init.raspbian
            awk -i inplace \
                  '1;/export PATH/{ print \
                  "export JAVA_HOME=$SNAP/jre\nexport PATH=$SNAP/jre/bin:$PATH"}' \
                kura/distrib/src/main/resources/common/kura.init.raspbian
            sed -i \
                  -e 's#/var/.monit.state#/var/snap/'"${SNAPCRAFT_PROJECT_NAME}"'/current/.monit.state#g' \
                  -e 's#/etc/init.d/kura#/snap/'"${SNAPCRAFT_PROJECT_NAME}"'/current/bin/kura-init#g' \
                kura/distrib/src/main/resources/common/monitrc.raspbian
            sed -i \
                  -e 's#monit=/usr/bin/monit#monit=${SNAP}/usr/bin/monit#g' \
                  -e 's#/etc/monitrc#${SNAP_COMMON}/etc/monitrc#g' \
                kura/distrib/src/main/resources/common/monit.init.raspbian
            sed -i \
                  -e 's#/etc/network/interfaces#${SNAP}/etc/network/interfaces#g' \
                  -e 's#/tmp/.kura#${SNAP_DATA}/tmp#g' \
                kura/distrib/src/main/resources/common/i*

        build: |
            ./build-all.sh $(mvn -N -f kura/distrib/pom.xml help:all-profiles | grep "Profile Id" | awk \
               -v profile=raspberry-pi-2-$(if [ "$(echo $SNAPCRAFT_PROJECT_NAME | tail -c 4)" = "-nn" ];then echo "3-nn"; else echo "3";fi) \
               '{ if($3 == profile){print "-P"$3}else{print "-P!"$3 }}' | sort -u | tr '\n' ' ')

        install: |
            unzip kura/distrib/target/kura_*_raspberry-pi-2$(if [ "$(echo $SNAPCRAFT_PROJECT_NAME | tail -c 4)" = "-nn" ];then echo "*-nn";fi).zip -d $SNAPCRAFT_PART_INSTALL/
            mv $SNAPCRAFT_PART_INSTALL/kura_* $SNAPCRAFT_PART_INSTALL/kura
            # tweak some config settings
            sed -i -e 's#-consoleLog >> /var/log/kura-.*#-consoleLog#g' \
                   -e 's#/tmp/.kura#${SNAP_DATA}/tmp#g' \
                   -e 's#${DIR}/data#${SNAP_COMMON}/data#g' \
                   -e 's#/var/log#${SNAP_DATA}/log#g' \
                   -e 's#-Dkura.configuration\=.*#-Dkura.configuration=file:${SNAP_COMMON}/conf/kura.properties \\#g' \
                   -e 's#-Dkura.custom.configuration\=.*#-Dkura.custom.configuration=file:${SNAP_COMMON}/conf/kura_custom.properties \\#g' \
                   -e 's#-Ddpa.configuration\=.*#-Ddpa.configuration=${SNAP_COMMON}/conf/dpa.properties \\#g' \
                   -e 's#-Dlog4j.configuration\=.*#-Dlog4j.configuration=file:${SNAP_COMMON}/conf/log4j.properties \\#g' \
                   -e 's#-Dkura.os.version\=.*#-Dkura.os.version=ubuntucore \\#g' \
                   -e 's#-Dtarget.device\=.*#-Dtarget.device=core \\#g' \
                   -e 's#/var/run/kura.pid#/$SNAP_DATA/run/kura.pid#g' \
                   -e 's#-Xms[0-9]*m#-Xms${JAVA_MEMORY}m#g' \
                   -e 's#-Xmx[0-9]*m#-Xmx${JAVA_MEMORY}m#g' \
                   $SNAPCRAFT_PART_INSTALL/kura/bin/start_kura*.sh
            awk -i inplace \
                  '1;/\/kura\/config.ini/{ print ". $SNAP/bin/read-config"}' $SNAPCRAFT_PART_INSTALL/kura/bin/start_kura*.sh
            chmod +x $SNAPCRAFT_PART_INSTALL/kura/install/*.raspbian
            chmod +x $SNAPCRAFT_PART_INSTALL/kura/install/*.init
        organize:
            kura/install/kura.init.raspbian: bin/kura-init
            kura/install/monit.init.raspbian: bin/monit-init
            kura/install/firewall.init: bin/firewall-init
            kura/install/iptables.init: etc/sysconfig/iptables
            kura/install/ifup-local.debian: etc/network/if-up.d/ifup-local
            kura/install/ifdown-local: etc/network/if-down.d/ifdown-local
            kura/install/network.interfaces.raspbian: etc/network/interfaces

    # start-stop-daemon
    start-stop-daemon:
        plugin: nil
        stage-packages:
            - dpkg
        stage:
            - -urs
            - -var
            - -etc

    # network
    net:
        plugin: nil
        stage-packages:
            - bind9
            - hostapd
            - isc-dhcp-server
            - iw
            - ethtool
            - wireless-tools
        install: |
            # fix bind9 and dependencies
            sed -i -e 's#/usr/sbin/#${SNAP}/usr/sbin/#g' \
                   -e 's#/run/named/#{SNAP_DATA}/named#g' \
                   -e 's#/run/named#{SNAP_DATA}/run/named#g' \
                   -e 's|chown.*|# chown: not allowed from snap|g' \
                   $SNAPCRAFT_PART_INSTALL/etc/init.d/bind9
            awk -i inplace '1;/RESOLVCONF=no/{ print "echo \"SNAP=${SNAP}\""}' \
                   $SNAPCRAFT_PART_INSTALL/etc/init.d/bind9

    # java run time
    jre:
        plugin: zulu-jre
        # zulu supported architectures(armhf, amd64) are already handled by plugin itself
        # define here overide for pluging's defaults, or to add additional architectures
        # example overide:
        # zulu:
        #     amd64: https://www.azul.com/downloads/zulu/zdk-8-ga-linux_x64.tar.gz

    helpers:
        plugin: dump
        source: scripts
    bluez:
        plugin: autotools
        source: https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/bluez
        source-type: git
        source-branch: bluez/5.44
        configflags:
           - --prefix=/usr
           - --libexec=/usr/lib/
           - --enable-experimental
           - --enable-threads
           - --disable-cups
           - --enable-obex
           - --disable-systemd
           - --disable-silent-rules
           - --enable-test
           - --enable-deprecated
        build-packages:
           - libglib2.0-dev
           - libdbus-1-dev
           - libical-dev
           - libreadline6-dev
           - libudev-dev
           - udev
           - pkg-config
        stage-packages:
           - libical1a
        filesets:
           libical1a:
             - usr/lib/*/libical*
        stage:
           - usr/lib/bluetooth/bluetoothd
           - usr/lib/bluetooth/obexd
           - usr/bin/bluetoothctl
           - usr/bin/obexctl
           - usr/bin/hciconfig
           - usr/bin/hcidump
           - usr/bin/hciattach
           - usr/bin/hcitool
           - usr/bin/sdptool
           - usr/bin/btmon
           - usr/bin/btmgmt
           - usr/share/doc/libical1a/copyright
           - $libical1a
