#!/bin/bash

echo "This is helper script and it shoud be called by user directly!"
echo "Connecting interfaces for kura"

snap connect kura:home core
snap connect kura:io-ports-control core
snap connect kura:hardware-observe core
snap connect kura:firewall-control core
snap connect kura:network-bind core
snap connect kura:network-control core
snap connect kura:network-manager core
snap connect kura:network-setup-control core
snap connect kura:process-control core
snap connect kura:removable-media core
snap connect kura:system-observe core
snap connect kura:time-control core
