#!/bin/bash

source $SNAP/snap/config &>/dev/null

echo -e "Kura: "
# parse config file for supported settings keys
echo -e "kura supports settings keys"
echo -e "values can be changed by calling\n$ snap set $SNAP_NAME <key name>='<key value>'"
echo -e "list of supported keys:"
if value=$(snapctl get java-memory); then
   echo Java memory is $value
else
   echo Jave memory not defined
fi
for key in ${keys[@]}
do
    default_value="DEFAULT_$key"
    description="DESCRIPTION_$key"
    snappy_key="KEY_$key"
    echo -e "\t${!snappy_key}:   ${!description}"
    value=$(snapctl get ${!snappy_key})
    if [ "x$value" == "x" ]; then
        echo -e "\t\tNo value set, using default value: '${!default_value}'"
    else
        echo -e "\t\tCurrent value set to: '$value', (default value: '${!default_value}')"
    fi
done

echo -e "\nFor changes to take effect restart kura"
