name: kura-nn

summary: Eclipse Kura™, An OSGi-based Application Framework for M2M Service Gateways
description: |
   Until recently, machine-to-machine projects have been approached as embedded systems
   designed around custom hardware, custom software, and custom network connectivity.
   The challenge of developing such projects was given by the large customization
   and integration costs and the small re-usability across similar engagements.
   The results were often proprietary systems leveraging proprietary protocols.

confinement: strict
grade: stable
adopt-info: kura
base: core18

environment:
    JAVA_HOME: $SNAP/jre
    PATH: $SNAP/jre/bin:$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
    LD_LIBRARY_PATH: $SNAP/lib:$SNAP/usr/lib:$SNAP_LIBRARY_PATH:$SNAP/lib/${SNAPCRAFT_ARCH_TRIPLET}:$SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}:$LD_LIBRARY_PATH

apps:
    kura:
        command: kura/bin/start_kura_snap.sh
        adapter: none
        daemon: simple
        plugs: 
            - bluez
            - bluetooth-control
            - gpio
            - hardware-observe
            - home
            - i2c
            - io-ports-control
            - log-observe
            - mount-observe
            - netlink-audit
            - network
            - network-bind
            - ppp
            - process-control
            - raw-usb
            - removable-media
            - serial-port
            - spi
            - shutdown
            - system-observe
            - time-control

    debug:
        command: kura/bin/start_kura_snap_debug.sh
        adapter: none
        plugs:
            - bluez
            - bluetooth-control
            - gpio
            - hardware-observe
            - home
            - i2c
            - io-ports-control
            - log-observe
            - mount-observe
            - netlink-audit
            - network
            - network-bind
            - ppp
            - process-control
            - raw-usb
            - removable-media
            - serial-port
            - spi
            - shutdown
            - system-observe
            - time-control

    monit:
        command: usr/bin/monit -I -c $SNAP_COMMON/etc/monitrc
        stop-command: usr/bin/monit -c $SNAP_COMMON/etc/monitrc quit
        adapter: none
        daemon: simple
        plugs:
            - process-control
            - system-observe

    help:
        command: bin/snap-help
        adapter: none



