#!/bin/bash

populate_writable_data() {
  mkdir -p ${SNAP_DATA}/log
  mkdir -p ${SNAP_DATA}/run
  mkdir -p ${SNAP_COMMON}/console
  mkdir -p ${SNAP_COMMON}/packages
  mkdir -p ${SNAP_COMMON}/.data
  if [ ! -d ${SNAP_COMMON}/conf ]; then
      mkdir -p ${SNAP_COMMON}/conf
      cp ${SNAP}/kura/kura/kura*.properties ${SNAP_COMMON}/conf
      cp ${SNAP}/kura/kura/dpa*.properties ${SNAP_COMMON}/conf
      cp ${SNAP}/kura/kura/log*.properties ${SNAP_COMMON}/conf
  fi

  cp ${SNAP}/kura/install/recover_default_config.init ${SNAP_COMMON}/.data/.recoverDefaultConfig.sh
  chmod +x ${SNAP_COMMON}/.data/.recoverDefaultConfig.sh


  mkdir -p ${SNAP_COMMON}/etc/bind
  cp ${SNAP}/kura/install/monitrc.raspbian ${SNAP_COMMON}/etc/monitrc
  chmod 700 ${SNAP_COMMON}/etc/monitrc

  cp ${SNAP}/kura/install/named.conf ${SNAP_COMMON}/etc/bind
  sed -i 's#/etc/bind/#${SNAP_COMMON}/etc/bind/#g' ${SNAP_COMMON}/etc/bind/*
  sed -i -e 's#/var/named#${SNAP_COMMON}/named#g' \
         -e 's#/var/log/named.log#{SNAP_DATA}/log/named.log#g' \
         -e 's#/etc/named#{SNAP_COMMON}/etc/bind/named#g' \
         ${SNAP_COMMON}/etc/bind/named.conf

  mkdir -p ${SNAP_COMMON}/named
  touch {SNAP_DATA}/log/named.log
  cp ${SNAP}/kura/install/named.ca ${SNAP_COMMON}/named/
  cp ${SNAP}/kura/install/named.rfc1912.zones ${SNAP_COMMON}/etc/bind/named.rfc1912.zones
  if [ ! -f " ${SNAP_COMMON}/etc/bind/rndc.key" ] ; then
  	rndc-confgen -r /dev/urandom -a -c ${SNAP_COMMON}/etc/named.iscdlv.key
  fi

  mac_addr=$(head -1 /sys/class/net/eth0/address | tr '[:lower:]' '[:upper:]')
  sed "s/^ssid=kura_gateway.*/ssid=kura_gateway_${mac_addr}/" < ${SNAP}/kura/install/hostapd.conf > ${SNAP_COMMON}/etc/hostapd-wlan0.conf
  cp ${SNAP_COMMON}/etc/hostapd-wlan0.conf ${SNAP_COMMON}/.data/hostapd-wlan0.conf

  cp ${SNAP}/kura/install/dhcpd-eth0.conf ${SNAP_COMMON}/etc/dhcpd-eth0.conf
  cp ${SNAP}/kura/install/dhcpd-eth0.conf ${SNAP_COMMON}/.data/dhcpd-eth0.conf

  cp ${SNAP}/kura/install/dhcpd-wlan0.conf ${SNAP_COMMON}/etc/dhcpd-wlan0.conf
  cp ${SNAP}/kura/install/dhcpd-wlan0.conf ${SNAP_COMMON}/.data/dhcpd-wlan0.conf

  if [ ! -d ${SNAP_COMMON}/data ]; then
      cp -r ${SNAP}/kura/data ${SNAP_COMMON}
      cp ${SNAP}/kura/install/kuranet.conf ${SNAP_COMMON}/data/kuranet.conf
      cp ${SNAP}/kura/install/kuranet.conf ${SNAP_COMMON}/.data/kuranet.conf
  fi

  # copy ${SNAP}/etc/network/if* to /etc/network, we can write there,
  # and Ubuntu core won't do anything with those scripts anyway
  #  cp -r $SNAP/etc/network/if-* /etc/network


  mkdir -p ${SNAP_COMMON}/etc/sysconfig
  cp ${SNAP}/kura/install/iptables.init ${SNAP_COMMON}/etc/sysconfig/iptables
  cp /etc/sysconfig/iptables ${INSTALL_DIR}/kura/.data/iptables

}

fix_file_paths() {
  # corect paths in properties
  sed -i -e 's#appender.kura.File=.*/kura.log#appender.kura.File='"${SNAP_DATA}"'/log/kura.log#g' \
         -e 's#appender.kura.RollingPolicy.ActiveFileName=.*/kura.log#appender.kura.RollingPolicy.ActiveFileName='"${SNAP_DATA}"'/log/kura.log#g' \
         -e 's#appender.kura.RollingPolicy.FileNamePattern=.*#appender.kura.RollingPolicy.FileNamePattern='"${SNAP_DATA}"'/log/kura-%i.log.gz#g' \
         ${SNAP_COMMON}/conf/log*.properties
  sed -i -e 's#kura.home=/.*#kura.home='"${SNAP}"'/kura/kura#g' \
         -e 's#kura.plugins=/.*#kura.plugins='"${SNAP}"'/kura/kura/plugins#g' \
         -e 's#kura.packages=/.*#kura.packages='"${SNAP_COMMON}"'/packages#g' \
         -e 's#kura.data=/.*#kura.data='"${SNAP_COMMON}"'/data#g' \
         -e 's#kura.tmp=/.*#kura.tmp='"${SNAP_DATA}"'/tmp#g' \
         -e 's#kura.snapshots=/.*#kura.snapshots='"${SNAP_COMMON}"'/data/snapshots#g' \
         -e 's#kura.style.dir=/.*#kura.style.dir='"${SNAP_COMMON}"'/console/skin#g' \
         ${SNAP_COMMON}/conf/kura.properties
}


